name: Run security scans and plan

on:
    pull_request:
        types: [opened, synchronize]
        branches: [main]

permissions:
  pull-requests: write

env:
# verbosity setting for Terraform logs
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    run-scans:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        
        - name: Install terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.12.2"
        
        - name: Terraform fmt
          id: fmt
          run: terraform fmt -check
          continue-on-error: true
        
        - name: Terraform init
          id: init
          run: terraform init
        
        # - name: Run terrascan
        #   id: terrascan
        #   uses: tenable/terrascan-action@main
        #   with:
        #     iac_type: 'terraform'
        #     iac_version: 'v13'
        #     policy_type: 'aws'
        #     only_warn: false
        #     sarif_upload: true

        - name: Install Terrascan
          run: |
            curl -L https://github.com/tenable/terrascan/releases/latest/download/terrascan_linux_amd64 -o terrascan
            chmod +x terrascan
            sudo mv terrascan /usr/local/bin/

        - name: Run Terrascan and Fail on Medium/High
          run: |
            terrascan scan -i terraform -t aws -o json > terrascan-result.json

            echo "Terrascan results:"
            cat terrascan-result.json

            HIGH=$(grep -o '"severity":"HIGH"' terrascan-result.json | wc -l)
            MEDIUM=$(grep -o '"severity":"MEDIUM"' terrascan-result.json | wc -l)

            if [ "$HIGH" -gt 0 ] || [ "$MEDIUM" -gt 0 ]; then
            echo "❌ Found $HIGH HIGH and $MEDIUM MEDIUM severity vulnerabilities."
            exit 1
            else
            echo "✅ No MEDIUM or HIGH severity issues found."
            fi

        - name: Terraform plan
          id: plan
          run: terraform plan > plan.txt

        - name: Install GitHub CLI
          run: |
            sudo apt-get update
            sudo apt-get install -y gh

        - name: Post Plan Output to PR
          run: |
            gh pr comment ${{ github.event.pull_request.number }} --body-file plan.txt
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}