name: Run security scans and plan

on:
    pull_request:
        types: [opened, synchronize]
        branches: [main]

permissions:
  pull-requests: write

env:
# verbosity setting for Terraform logs
 TF_LOG: INFO
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    run-scans:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        
        - name: Install terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: "1.12.2"

        - name: Install jq
          run: sudo apt-get install -y jq

        - name: Install GitHub CLI
          run: |
            sudo apt-get update
            sudo apt-get install -y gh
        
        - name: Terraform fmt
          id: fmt
          run: terraform fmt
          continue-on-error: true
        
        - name: Terraform init
          id: init
          run: terraform init
        
        - name: Run Checkov action
          id: checkov
          uses: bridgecrewio/checkov-action@master
          with:
            soft_fail: false
            framework: terraform
            output_format: sarif
            output_file_path: reports/results.sarif

        - name: Terraform plan
          id: plan
          run: terraform plan > plan.txt

        - name: Post Plan Output to PR
          run: |
            gh pr comment ${{ github.event.pull_request.number }} --body-file plan.txt
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}